version: '3'

services:
  postgres:
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: productionpassword
      POSTGRES_DB: productiondb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "productiondb"]

  drf-app:
    build: 
      target: production
    entrypoint: ./entrypoint.sh
    scale: 2

volumes:
  postgres_prod_data: