# Generated by Django 5.0.4 on 2024-04-25 12:20

import users.models.candidate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_candidate_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to=users.models.candidate.candidate_image_upload),
        ),
    ]
