# Generated by Django 5.0.4 on 2024-04-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
