# Generated by Django 5.0.4 on 2024-04-26 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
