# Generated by Django 5.0.4 on 2024-04-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_vote_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='uuid',
        ),
    ]
